// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as DataService from "./dataservice.js";
export {
    DataService
};

export * from "./models.js";
