// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetSettings(): Promise<$models.SettingsValues> & { cancel(): void } {
    let $resultPromise = $Call.ByID(4188995328) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType0($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function OnShutdown(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(921268848) as any;
    return $resultPromise;
}

export function ResetSetting(key: string[]): Promise<any> & { cancel(): void } {
    let $resultPromise = $Call.ByID(373731326, key) as any;
    return $resultPromise;
}

export function UpdateSetting(key: string[], val: any): Promise<boolean> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3662822206, key, val) as any;
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = $models.SettingsValues.createFrom;
