package scripture
// DO NOT EDIT - THIS FILE IS AUTOGENERATED

type ScriptureRef int

type BookData struct {
  Name          string
  Short         string
  Abbreviations []string
}

type VersionBibleRange struct {
  Start ScriptureRef
  End   ScriptureRef
}

type VersionBookData struct {
  BookNumber      int
  DisplayName     string
  NumChapters     int
  NumVerses       []int
  Superscripts    []int
  Prologue        int
  Parallels       []VersionBibleRange
  MissingSections []VersionBibleRange
}

type VersionData struct {
  Name             string
  FullName         string
  Language         string
  LanguageHeadings string
  Books            []VersionBookData
}

var BibleData = [...]BookData{
  {
    Name: "Genesis",
    Short: "Gen",
    Abbreviations: []string{
      "Genesis",
      "Gen",
      "Ge",
      "Gn",
    },
  },
  {
    Name: "Exodus",
    Short: "Exo",
    Abbreviations: []string{
      "Exodus",
      "Exo",
      "Ex",
      "Exod",
    },
  },
  {
    Name: "Leviticus",
    Short: "Lev",
    Abbreviations: []string{
      "Leviticus",
      "Lev",
      "Leviticus",
      "Lev",
    },
  },
  {
    Name: "Numbers",
    Short: "Num",
    Abbreviations: []string{
      "Numbers",
      "Num",
      "Nu",
      "Nm",
      "Nb",
    },
  },
  {
    Name: "Deuteronomy",
    Short: "Deut",
    Abbreviations: []string{
      "Deuteronomy",
      "Deut",
      "De",
      "Dt",
    },
  },
  {
    Name: "Joshua",
    Short: "Josh",
    Abbreviations: []string{
      "Joshua",
      "Josh",
      "Jos",
      "Jsh",
    },
  },
  {
    Name: "Judges",
    Short: "Judg",
    Abbreviations: []string{
      "Judges",
      "Judg",
      "Jdg",
      "Jg",
      "Jdgs",
    },
  },
  {
    Name: "Ruth",
    Short: "Ruth",
    Abbreviations: []string{
      "Ruth",
      "Ruth",
      "Rth",
      "Ru",
    },
  },
  {
    Name: "1 Samuel",
    Short: "1Sam",
    Abbreviations: []string{
      "1 Samuel",
      "1Sam",
      "1 Sam",
      "1 Sm",
      "1Sm",
      "1 Sa",
      "1Sa",
      "1 S",
      "1S",
      "I Sam",
      "ISam",
      "I Sa",
      "1Samuel",
      "1st Samuel",
      "1st Sam",
      "First Samuel",
      "First Sam",
    },
  },
  {
    Name: "2 Samuel",
    Short: "2Sam",
    Abbreviations: []string{
      "2 Samuel",
      "2Sam",
      "2 Sam",
      "2 Sm",
      "2Sm",
      "2 Sa",
      "2Sa",
      "2 S",
      "2S",
      "II Sam",
      "IISam",
      "II Sa",
      "IISa",
      "2Samuel",
      "2nd Samuel",
      "2nd Sam",
      "Second Samuel",
      "Second Sam",
    },
  },
  {
    Name: "1 Kings",
    Short: "1Ki",
    Abbreviations: []string{
      "1 Kings",
      "1Ki",
      "1 Ki",
      "1 Kgs",
      "1Kgs",
      "1 Kin",
      "1Kin",
      "1 K",
      "1K",
      "I Kgs",
      "IKgs",
      "I Ki",
      "IKi",
      "1Kings",
      "1st Kings",
      "1st Kgs",
      "First Kings",
      "First Kgs",
    },
  },
  {
    Name: "2 Kings",
    Short: "2Ki",
    Abbreviations: []string{
      "2 Kings",
      "2Ki",
      "2 Ki",
      "2 Kgs",
      "2Kgs",
      "2 Kin",
      "2Kin",
      "2 K",
      "2K",
      "II Kgs",
      "IIKgs",
      "II Ki",
      "IIKi",
      "2Kings",
      "2nd Kings",
      "2nd Kgs",
      "Second Kings",
      "Second Kgs",
    },
  },
  {
    Name: "1 Chronicles",
    Short: "1Chr",
    Abbreviations: []string{
      "1 Chronicles",
      "1Chr",
      "1 Chr",
      "1 Chron",
      "1Chron",
      "1 Ch",
      "1Ch",
      "I Chron",
      "IChron",
      "I Chr",
      "IChr",
      "I Ch",
      "ICh",
      "1Chronicles",
      "1st Chronicles",
      "1st Chron",
      "First Chronicles",
      "First Chron",
    },
  },
  {
    Name: "2 Chronicles",
    Short: "2Chr",
    Abbreviations: []string{
      "2 Chronicles",
      "2Chr",
      "2 Chr",
      "2 Chron",
      "2Chron",
      "2 Ch",
      "2Ch",
      "II Chron",
      "IIChron",
      "II Chr",
      "IIChr",
      "II Ch",
      "IICh",
      "2Chronicles",
      "2nd Chronicles",
      "2nd Chron",
      "Second Chronicles",
      "Second Chron",
    },
  },
  {
    Name: "Ezra",
    Short: "Ezra",
    Abbreviations: []string{
      "Ezra",
      "Ezr",
      "Ez",
    },
  },
  {
    Name: "Nehemiah",
    Short: "Neh",
    Abbreviations: []string{
      "Nehemiah",
      "Neh",
      "Ne",
      "Nem",
    },
  },
  {
    Name: "Esther",
    Short: "Esth",
    Abbreviations: []string{
      "Esther",
      "Esth",
      "Es",
      "Est",
    },
  },
  {
    Name: "Job",
    Short: "Job",
    Abbreviations: []string{
      "Job",
      "Jb",
    },
  },
  {
    Name: "Psalms",
    Short: "Psa",
    Abbreviations: []string{
      "Psalms",
      "Psa",
      "Psalm",
      "Pslm",
      "Psm",
      "Pss",
      "Ps",
    },
  },
  {
    Name: "Proverbs",
    Short: "Prov",
    Abbreviations: []string{
      "Proverbs",
      "Prov",
      "Pro",
      "Prv",
      "Pr",
    },
  },
  {
    Name: "Ecclesiastes",
    Short: "Eccl",
    Abbreviations: []string{
      "Ecclesiastes",
      "Eccl",
      "Eccles",
      "Eccle",
      "Ecc",
      "Qoh",
      "Qoheleth",
      "Kohelet",
    },
  },
  {
    Name: "Song of Songs",
    Short: "Song",
    Abbreviations: []string{
      "Song of Songs",
      "Song",
      "Song of Solomon",
      "SOS",
      "SoS",
      "So",
      "Canticle of Canticles",
      "Canticles",
      "Cant",
    },
  },
  {
    Name: "Isaiah",
    Short: "Isa",
    Abbreviations: []string{
      "Isaiah",
      "Isa",
      "Is",
    },
  },
  {
    Name: "Jeremiah",
    Short: "Jer",
    Abbreviations: []string{
      "Jeremiah",
      "Jer",
      "Je",
      "Jr",
    },
  },
  {
    Name: "Lamentations",
    Short: "Lam",
    Abbreviations: []string{
      "Lamentations",
      "Lam",
      "La",
    },
  },
  {
    Name: "Ezekiel",
    Short: "Ezek",
    Abbreviations: []string{
      "Ezekiel",
      "Ezek",
      "Eze",
      "Ezk",
    },
  },
  {
    Name: "Daniel",
    Short: "Dan",
    Abbreviations: []string{
      "Daniel",
      "Dan",
      "Da",
      "Dn",
    },
  },
  {
    Name: "Hosea",
    Short: "Hos",
    Abbreviations: []string{
      "Hosea",
      "Hos",
      "Ho",
    },
  },
  {
    Name: "Joel",
    Short: "Joel",
    Abbreviations: []string{
      "Joel",
      "Jl",
    },
  },
  {
    Name: "Amos",
    Short: "Amos",
    Abbreviations: []string{
      "Amos",
      "Am",
    },
  },
  {
    Name: "Obadiah",
    Short: "Obad",
    Abbreviations: []string{
      "Obadiah",
      "Obad",
      "Ob",
    },
  },
  {
    Name: "Jonah",
    Short: "Jonah",
    Abbreviations: []string{
      "Jonah",
      "Jnh",
      "Jon",
    },
  },
  {
    Name: "Micah",
    Short: "Mic",
    Abbreviations: []string{
      "Micah",
      "Mic",
      "Mc",
    },
  },
  {
    Name: "Nahum",
    Short: "Nah",
    Abbreviations: []string{
      "Nahum",
      "Nah",
      "Na",
    },
  },
  {
    Name: "Habakkuk ",
    Short: "Hab",
    Abbreviations: []string{
      "Habakkuk ",
      "Hab",
      "Hb",
    },
  },
  {
    Name: "Zephaniah",
    Short: "Zeph",
    Abbreviations: []string{
      "Zephaniah",
      "Zeph",
      "Zep",
      "Zp",
    },
  },
  {
    Name: "Haggai",
    Short: "Hag",
    Abbreviations: []string{
      "Haggai",
      "Hag",
      "Hg",
    },
  },
  {
    Name: "Zechariah",
    Short: "Zech",
    Abbreviations: []string{
      "Zechariah",
      "Zech",
      "Zec",
      "Zc",
    },
  },
  {
    Name: "Malachi",
    Short: "Mal",
    Abbreviations: []string{
      "Malachi",
      "Mal",
      "Ml",
    },
  },
  {
    Name: "Matthew",
    Short: "Matt",
    Abbreviations: []string{
      "Matthew",
      "Matt",
      "Mt",
    },
  },
  {
    Name: "Mark",
    Short: "Mark",
    Abbreviations: []string{
      "Mark",
      "Mark",
      "Mrk",
      "Mar",
      "Mk",
      "Mr",
    },
  },
  {
    Name: "Luke",
    Short: "Luke",
    Abbreviations: []string{
      "Luke",
      "Luk",
      "Lk",
    },
  },
  {
    Name: "John",
    Short: "John",
    Abbreviations: []string{
      "John",
      "Joh",
      "Jhn",
      "Jn",
    },
  },
  {
    Name: "Acts",
    Short: "Acts",
    Abbreviations: []string{
      "Acts",
      "Act",
      "Ac",
    },
  },
  {
    Name: "Romans",
    Short: "Rom",
    Abbreviations: []string{
      "Romans",
      "Rom",
      "Ro",
      "Rm",
    },
  },
  {
    Name: "1 Corinthians",
    Short: "1Cor",
    Abbreviations: []string{
      "1 Corinthians",
      "1Cor",
      "1 Cor",
      "1Corinthians",
      "1 Co",
      "1Co",
      "I Cor",
      "ICor",
      "I Co",
      "ICo",
      "I Corinthians",
      "ICorinthians",
      "1st Corinthians",
      "First Corinthians",
    },
  },
  {
    Name: "2 Corinthians",
    Short: "2Cor",
    Abbreviations: []string{
      "2 Corinthians",
      "2Cor",
      "2 Cor",
      "2Corinthians",
      "2 Co",
      "2Co",
      "II Cor",
      "IICor",
      "II Co",
      "IICo",
      "II Corinthians",
      "IICorinthians",
      "2nd Corinthians",
      "Second Corinthians",
    },
  },
  {
    Name: "Galatians",
    Short: "Gal",
    Abbreviations: []string{
      "Galatians",
      "Gal",
      "Ga",
    },
  },
  {
    Name: "Ephesians",
    Short: "Eph",
    Abbreviations: []string{
      "Ephesians",
      "Eph",
      "Ephes",
      "Ep",
    },
  },
  {
    Name: "Philippians",
    Short: "Phil",
    Abbreviations: []string{
      "Philippians",
      "Phil",
      "Phi",
      "Php",
      "Pp",
    },
  },
  {
    Name: "Colossians",
    Short: "Col",
    Abbreviations: []string{
      "Colossians",
      "Col",
      "Co",
    },
  },
  {
    Name: "1 Thessalonians",
    Short: "1Th",
    Abbreviations: []string{
      "1 Thessalonians",
      "1Th",
      "1Thessalonians",
      "1 Th",
      "1 Thess",
      "1Thess",
      "1 Thes",
      "1Thes",
      "I Thessalonians",
      "IThessalonians",
      "I Thess",
      "IThess",
      "I Thes",
      "IThes",
      "I Th",
      "ITh",
      "1st Thessalonians",
      "1st Thess",
      "1st Thes",
      "First Thessalonians",
      "First Thess",
      "First Thes",
    },
  },
  {
    Name: "2 Thessalonians",
    Short: "2Th",
    Abbreviations: []string{
      "2 Thessalonians",
      "2Th",
      "2Thessalonians",
      "2 Th",
      "2 Thess",
      "2Thess",
      "2 Thes",
      "2Thes",
      "II Thessalonians",
      "IIThessalonians",
      "II Thess",
      "IIThess",
      "II Thes",
      "IIThes",
      "II Th",
      "IITh",
      "2nd Thessalonians",
      "2nd Thess",
      "2nd Thes",
      "Second Thessalonians",
      "Second Thess",
      "Second Thes",
    },
  },
  {
    Name: "1 Timothy",
    Short: "1Tim",
    Abbreviations: []string{
      "1 Timothy",
      "1Tim",
      "1Timothy",
      "1 Tim",
      "1Ti",
      "1 Ti",
      "I Timothy",
      "ITimothy",
      "I Tim",
      "ITim",
      "1st Timothy",
      "1st Tim",
      "First Timothy",
      "First Tim",
    },
  },
  {
    Name: "2 Timothy",
    Short: "2Tim",
    Abbreviations: []string{
      "2 Timothy",
      "2Tim",
      "2Timothy",
      "2 Tim",
      "2Ti",
      "2 Ti",
      "II Timothy",
      "IITimothy",
      "II Tim",
      "IITim",
      "2nd Timothy",
      "2nd Tim",
      "Second Timothy",
      "Second Tim",
    },
  },
  {
    Name: "Titus",
    Short: "Titus",
    Abbreviations: []string{
      "Titus",
      "Tit",
      "Ti",
    },
  },
  {
    Name: "Philemon",
    Short: "Phlm",
    Abbreviations: []string{
      "Philemon",
      "Phlm",
      "Philem",
      "Pm",
    },
  },
  {
    Name: "Hebrews",
    Short: "Heb",
    Abbreviations: []string{
      "Hebrews",
      "Heb",
      "He",
    },
  },
  {
    Name: "James",
    Short: "Jas",
    Abbreviations: []string{
      "James",
      "Jas",
      "Jm",
      "Jam",
    },
  },
  {
    Name: "1 Peter",
    Short: "1Pet",
    Abbreviations: []string{
      "1 Peter",
      "1Pet",
      "1Peter",
      "1 Pet",
      "1 Pe",
      "1Pe",
      "1 P",
      "1P",
      "I Pet",
      "IPet",
      "I Pe",
      "IPe",
      "I P",
      "IP",
      "1st Peter",
      "First Peter",
    },
  },
  {
    Name: "2 Peter",
    Short: "2Pet",
    Abbreviations: []string{
      "2 Peter",
      "2Pet",
      "2Peter",
      "2 Pet",
      "2 Pe",
      "2Pe",
      "2 P",
      "2P",
      "II Pet",
      "IIPet",
      "II Pe",
      "IIPe",
      "II P",
      "IIP",
      "2nd Peter",
      "Second Peter",
    },
  },
  {
    Name: "1 John",
    Short: "1Jo",
    Abbreviations: []string{
      "1 John",
      "1Jo",
      "1John",
      "1 Jo",
      "1 Jhn",
      "1Jhn",
      "1 Jn",
      "1Jn",
      "1 J",
      "1J",
      "1 Joh",
      "1Joh",
      "I John",
      "IJohn",
      "I Jhn",
      "IJhn",
      "I Joh",
      "IJoh",
      "I Jn",
      "IJn",
      "I Jo",
      "IJo",
      "1st John",
      "First John",
    },
  },
  {
    Name: "2 John",
    Short: "2Jo",
    Abbreviations: []string{
      "2 John",
      "2Jo",
      "2John",
      "2 Jo",
      "2 Jhn",
      "2Jhn",
      "2 Jn",
      "2Jn",
      "2 J",
      "2J",
      "2 Joh",
      "2Joh",
      "II John",
      "IIJohn",
      "II Jhn",
      "IIJhn",
      "II Joh",
      "IIJoh",
      "II Jn",
      "IIJn",
      "II Jo",
      "IIJo",
      "2nd John",
      "Second John",
    },
  },
  {
    Name: "3 John",
    Short: "3Jo",
    Abbreviations: []string{
      "3 John",
      "3Jo",
      "3John",
      "3 Jo",
      "3 Jhn",
      "3Jhn",
      "3 Jn",
      "3Jn",
      "3 J",
      "3J",
      "3 Joh",
      "3Joh",
      "III John",
      "IIIJohn",
      "III Jhn",
      "IIIJhn",
      "III Joh",
      "IIIJoh",
      "III Jn",
      "IIIJn",
      "III Jo",
      "IIIJo",
      "3rd John",
      "Third John",
    },
  },
  {
    Name: "Jude",
    Short: "Jude",
    Abbreviations: []string{
      "Jude",
      "Jud",
      "Jd",
    },
  },
  {
    Name: "Revelation",
    Short: "Rev",
    Abbreviations: []string{
      "Revelation",
      "Rev",
      "Re",
      "The Revelation",
    },
  },
  {
    Name: "1 Esdras",
    Short: "1Esdr",
    Abbreviations: []string{
      "1 Esdras",
      "1Esdr",
    },
  },
  {
    Name: "Judith",
    Short: "Jdt",
    Abbreviations: []string{
      "Judith",
      "Jdt",
      "Jth",
      "Jdth",
    },
  },
  {
    Name: "Tobit",
    Short: "Tob",
    Abbreviations: []string{
      "Tobit",
      "Tob",
      "Tb",
    },
  },
  {
    Name: "1 Maccabees",
    Short: "1Mac",
    Abbreviations: []string{
      "1 Maccabees",
      "1Mac",
      "1 Maccabees",
      "1 Mac",
      "1 Macc",
      "1Macc",
      "1 Ma",
      "1Ma",
      "1 M",
      "1M",
      "I Maccabees",
      "IMaccabees",
      "I Macc",
      "IMacc",
      "I Mac",
      "IMac",
      "I Ma",
      "IMa",
      "I M",
      "IM",
      "1st Maccabees",
      "First Maccabees",
    },
  },
  {
    Name: "2 Maccabees",
    Short: "2Mac",
    Abbreviations: []string{
      "2 Maccabees",
      "2Mac",
      "2 Maccabees",
      "2 Mac",
      "2 Macc",
      "2Macc",
      "2 Ma",
      "2Ma",
      "2 M",
      "2M",
      "II Maccabees",
      "IIMaccabees",
      "II Macc",
      "IIMacc",
      "II Mac",
      "IIMac",
      "II Ma",
      "IIMa",
      "II M",
      "IIM",
      "2nd Maccabees",
      "Second Maccabees",
    },
  },
  {
    Name: "3 Maccabees",
    Short: "3Mac",
    Abbreviations: []string{
      "3 Maccabees",
      "3Mac",
      "3 Maccabees",
      "3 Mac",
      "3 Macc",
      "3Macc",
      "3 Ma",
      "3Ma",
      "3 M",
      "3M",
      "III Maccabees",
      "IIIMaccabees",
      "III Macc",
      "IIIMacc",
      "III Mac",
      "IIIMac",
      "III Ma",
      "IIIMa",
      "III M",
      "IIIM",
      "3rd Maccabees",
      "Third Maccabees",
    },
  },
  {
    Name: "4 Maccabees",
    Short: "4Mac",
    Abbreviations: []string{
      "4 Maccabees",
      "4Mac",
      "4 Maccabees",
      "4 Mac",
      "4 Macc",
      "4Macc",
      "4 Ma",
      "4Ma",
      "4 M",
      "4M",
      "IV Maccabees",
      "IVMaccabees",
      "IV Macc",
      "IVMacc",
      "IV Mac",
      "IVMac",
      "IV Ma",
      "IVMa",
      "IV M",
      "IVM",
      "4th Maccabees",
      "Fourth Maccabees",
    },
  },
  {
    Name: "Odes",
    Short: "Ode",
    Abbreviations: []string{
      "Odes",
      "Ode",
    },
  },
  {
    Name: "Wisdom of Solomon",
    Short: "Wis",
    Abbreviations: []string{
      "Wisdom of Solomon",
      "Wis",
      "Wisd of Sol",
      "Wisdom",
      "Ws",
    },
  },
  {
    Name: "Sirach",
    Short: "Sir",
    Abbreviations: []string{
      "Sirach",
      "Sir",
      "Ecclesiasticus",
    },
  },
  {
    Name: "Solomon",
    Short: "Sol",
    Abbreviations: []string{
      "Solomon",
      "Sol",
    },
  },
  {
    Name: "Baruch",
    Short: "Bar",
    Abbreviations: []string{
      "Baruch",
      "Bar",
    },
  },
  {
    Name: "Letter of Jeremiah",
    Short: "LeterJ",
    Abbreviations: []string{
      "Letter of Jeremiah",
      "LeterJ",
      "Ep Jer",
      "EpJer",
      "Let Jer",
      "LetJer",
      "Ltr Jer",
      "LtrJer",
      "LJe",
      "Letter Jer",
      "LetterJer",
    },
  },
  {
    Name: "Susanna",
    Short: "Sus",
    Abbreviations: []string{
      "Susanna",
      "Sus",
    },
  },
  {
    Name: "Bel and the Dragon",
    Short: "Bel",
    Abbreviations: []string{
      "Bel and the Dragon",
      "Bel",
      "Bel and Dr",
    },
  },
}

var VersionsData = [...]VersionData{
  {
    Name: "lxx",
    FullName: "Septuagint (LXX)",
    Language: "greek",
    LanguageHeadings: "english",
    Books: []VersionBookData{
      {
        BookNumber: 1,
        DisplayName: "Genesis",
        NumChapters: 50,
        NumVerses: []int{31,25,24,26,32,22,24,22,29,32,32,20,18,24,21,16,27,33,38,18,34,24,20,67,34,35,46,22,35,43,54,33,20,31,29,43,36,30,23,23,57,38,34,34,28,34,31,22,33,26},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
          {
            Start: 1031051,
            End: 1031051,
          },
          {
            Start: 1035021,
            End: 1035021,
          },
        },
      },
      {
        BookNumber: 2,
        DisplayName: "Exodus",
        NumChapters: 40,
        NumVerses: []int{22,25,22,31,23,30,29,28,35,29,10,51,22,31,27,36,16,27,25,26,37,30,33,18,40,37,21,43,46,38,18,35,23,35,35,38,21,27,23,38},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
          {
            Start: 2025006,
            End: 2025006,
          },
          {
            Start: 2028023,
            End: 2028028,
          },
          {
            Start: 2032009,
            End: 2032009,
          },
          {
            Start: 2035008,
            End: 2035008,
          },
          {
            Start: 2035015,
            End: 2035015,
          },
          {
            Start: 2035017,
            End: 2035018,
          },
          {
            Start: 2040007,
            End: 2040007,
          },
          {
            Start: 2040011,
            End: 2040011,
          },
          {
            Start: 2040028,
            End: 2040028,
          },
          {
            Start: 2040030,
            End: 2040032,
          },
        },
      },
      {
        BookNumber: 3,
        DisplayName: "Leviticus",
        NumChapters: 27,
        NumVerses: []int{17,16,17,35,26,23,38,36,24,20,47,8,59,57,33,34,16,30,37,27,24,33,44,23,55,46,34},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 4,
        DisplayName: "Numbers",
        NumChapters: 36,
        NumVerses: []int{54,34,51,49,31,26,89,26,23,36,35,16,33,45,41,35,28,32,22,29,35,41,30,25,18,65,23,31,39,17,54,42,56,29,34,13},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 5,
        DisplayName: "Deuteronomy",
        NumChapters: 34,
        NumVerses: []int{46,37,29,49,33,25,26,20,29,22,32,31,19,29,23,22,20,22,21,20,23,29,26,22,19,19,26,69,28,20,30,52,29,12},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 6,
        DisplayName: "Joshua",
        NumChapters: 24,
        NumVerses: []int{18,24,17,24,15,27,26,29,27,42,23,24,32,15,63,10,18,28,51,9,45,34,16,33},
        Prologue: 0,
        Parallels: []VersionBibleRange{
          {
            Start: 6015021,
            End: 6015062,
          },
          {
            Start: 6018021,
            End: 6018028,
          },
          {
            Start: 6019001,
            End: 6019045,
          },
        },
        MissingSections: []VersionBibleRange{
          {
            Start: 6006004,
            End: 6006004,
          },
          {
            Start: 6008013,
            End: 6008013,
          },
          {
            Start: 6008026,
            End: 6008026,
          },
          {
            Start: 6010015,
            End: 6010015,
          },
          {
            Start: 6020004,
            End: 6020006,
          },
        },
      },
      {
        BookNumber: 7,
        DisplayName: "Judges",
        NumChapters: 21,
        NumVerses: []int{36,23,31,24,31,40,25,35,57,18,40,15,25,20,20,31,13,31,30,48,25},
        Prologue: 0,
        Parallels: []VersionBibleRange{
          {
            Start: 7001001,
            End: 7001036,
          },
          {
            Start: 7002001,
            End: 7002023,
          },
          {
            Start: 7003001,
            End: 7003031,
          },
          {
            Start: 7004001,
            End: 7004024,
          },
          {
            Start: 7005001,
            End: 7005031,
          },
          {
            Start: 7006001,
            End: 7006040,
          },
          {
            Start: 7007001,
            End: 7007025,
          },
          {
            Start: 7008001,
            End: 7008035,
          },
          {
            Start: 7009001,
            End: 7009057,
          },
          {
            Start: 7010001,
            End: 7010018,
          },
          {
            Start: 7011001,
            End: 7011040,
          },
          {
            Start: 7012001,
            End: 7012015,
          },
          {
            Start: 7013001,
            End: 7013025,
          },
          {
            Start: 7014001,
            End: 7014020,
          },
          {
            Start: 7015001,
            End: 7015020,
          },
          {
            Start: 7016001,
            End: 7016031,
          },
          {
            Start: 7017001,
            End: 7017013,
          },
          {
            Start: 7018001,
            End: 7018031,
          },
          {
            Start: 7019001,
            End: 7019030,
          },
          {
            Start: 7020001,
            End: 7020048,
          },
          {
            Start: 7021001,
            End: 7021025,
          },
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 8,
        DisplayName: "Ruth",
        NumChapters: 4,
        NumVerses: []int{22,23,18,22},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 9,
        DisplayName: "1 Kingdoms",
        NumChapters: 31,
        NumVerses: []int{28,36,21,22,12,21,17,22,27,27,15,25,23,52,35,23,54,29,24,42,16,23,28,23,44,25,12,25,11,31,13},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
          {
            Start: 9013001,
            End: 9013001,
          },
          {
            Start: 9017012,
            End: 9017031,
          },
          {
            Start: 9017041,
            End: 9017041,
          },
          {
            Start: 9017050,
            End: 9017050,
          },
          {
            Start: 9018001,
            End: 9018005,
          },
          {
            Start: 9018010,
            End: 9018011,
          },
          {
            Start: 9018017,
            End: 9018019,
          },
          {
            Start: 9023012,
            End: 9023012,
          },
        },
      },
      {
        BookNumber: 10,
        DisplayName: "2 Kingdoms",
        NumChapters: 24,
        NumVerses: []int{27,32,39,12,25,23,29,18,13,19,27,31,39,33,37,23,29,32,44,26,22,51,39,25},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 11,
        DisplayName: "3 Kingdoms",
        NumChapters: 22,
        NumVerses: []int{53,46,28,19,32,36,50,66,28,29,43,33,34,31,34,34,24,46,21,29,43,54},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
          {
            Start: 11003001,
            End: 11003001,
          },
          {
            Start: 11005005,
            End: 11005008,
          },
          {
            Start: 11005031,
            End: 11005031,
          },
          {
            Start: 11006011,
            End: 11006014,
          },
          {
            Start: 11006018,
            End: 11006018,
          },
          {
            Start: 11008012,
            End: 11008013,
          },
          {
            Start: 11009015,
            End: 11009025,
          },
          {
            Start: 11011003,
            End: 11011003,
          },
          {
            Start: 11011023,
            End: 11011024,
          },
          {
            Start: 11011039,
            End: 11011039,
          },
          {
            Start: 11012002,
            End: 11012002,
          },
          {
            Start: 11012017,
            End: 11012017,
          },
          {
            Start: 11013027,
            End: 11013027,
          },
          {
            Start: 11014001,
            End: 11014020,
          },
          {
            Start: 11015006,
            End: 11015006,
          },
          {
            Start: 11015032,
            End: 11015032,
          },
          {
            Start: 11022047,
            End: 11022050,
          },
        },
      },
      {
        BookNumber: 12,
        DisplayName: "4 Kingdoms",
        NumChapters: 25,
        NumVerses: []int{18,25,27,44,27,33,20,29,37,36,20,22,25,29,38,20,41,37,37,21,26,20,37,20,30},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 13,
        DisplayName: "1 Chronicles",
        NumChapters: 29,
        NumVerses: []int{54,55,24,43,41,66,40,40,44,14,47,41,14,17,29,43,27,17,19,8,30,19,32,31,31,32,34,21,30},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
          {
            Start: 13001011,
            End: 13001016,
          },
          {
            Start: 13001018,
            End: 13001023,
          },
          {
            Start: 13016024,
            End: 13016024,
          },
        },
      },
      {
        BookNumber: 14,
        DisplayName: "2 Chronicles",
        NumChapters: 36,
        NumVerses: []int{18,17,17,22,14,42,22,18,31,19,23,16,23,14,19,14,19,34,11,37,20,12,21,27,28,23,9,27,36,27,21,33,25,33,27,23},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
          {
            Start: 14027008,
            End: 14027008,
          },
        },
      },
      {
        BookNumber: 67,
        DisplayName: "1 Esdras",
        NumChapters: 9,
        NumVerses: []int{55,26,24,63,71,33,15,92,55},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 15,
        DisplayName: "Ezra",
        NumChapters: 10,
        NumVerses: []int{11,70,13,24,17,22,28,36,15,44},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 16,
        DisplayName: "Nehemiah",
        NumChapters: 13,
        NumVerses: []int{11,20,37,17,19,19,73,18,37,40,36,47,31},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
          {
            Start: 16003007,
            End: 16003007,
          },
          {
            Start: 16011016,
            End: 16011016,
          },
          {
            Start: 16011020,
            End: 16011021,
          },
          {
            Start: 16011028,
            End: 16011029,
          },
          {
            Start: 16011032,
            End: 16011035,
          },
          {
            Start: 16012004,
            End: 16012006,
          },
        },
      },
      {
        BookNumber: 17,
        DisplayName: "Esther",
        NumChapters: 10,
        NumVerses: []int{22,23,15,17,14,14,10,17,32,3},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
          {
            Start: 17004006,
            End: 17004006,
          },
          {
            Start: 17009005,
            End: 17009005,
          },
          {
            Start: 17009030,
            End: 17009030,
          },
        },
      },
      {
        BookNumber: 68,
        DisplayName: "Judith",
        NumChapters: 16,
        NumVerses: []int{16,28,10,15,24,21,32,36,14,23,23,20,20,19,14,25},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 69,
        DisplayName: "Tobit",
        NumChapters: 14,
        NumVerses: []int{22,14,17,21,23,19,17,21,6,14,19,22,18,15},
        Prologue: 0,
        Parallels: []VersionBibleRange{
          {
            Start: 69001001,
            End: 69001022,
          },
          {
            Start: 69002001,
            End: 69002014,
          },
          {
            Start: 69003001,
            End: 69003017,
          },
          {
            Start: 69004001,
            End: 69004007,
          },
          {
            Start: 69004019,
            End: 69004021,
          },
          {
            Start: 69005001,
            End: 69005023,
          },
          {
            Start: 69006001,
            End: 69006019,
          },
          {
            Start: 69007001,
            End: 69007017,
          },
          {
            Start: 69008001,
            End: 69008021,
          },
          {
            Start: 69009001,
            End: 69009003,
          },
          {
            Start: 69009005,
            End: 69009006,
          },
          {
            Start: 69010001,
            End: 69010014,
          },
          {
            Start: 69011001,
            End: 69011019,
          },
          {
            Start: 69012001,
            End: 69012022,
          },
          {
            Start: 69013001,
            End: 69013007,
          },
          {
            Start: 69013011,
            End: 69013018,
          },
          {
            Start: 69014001,
            End: 69014008,
          },
          {
            Start: 69014010,
            End: 69014015,
          },
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 70,
        DisplayName: "1 Maccabees",
        NumChapters: 16,
        NumVerses: []int{64,70,60,61,68,63,50,32,73,89,74,53,53,49,41,24},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 71,
        DisplayName: "2 Maccabees",
        NumChapters: 15,
        NumVerses: []int{36,32,40,50,27,31,42,36,29,38,38,45,26,46,39},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 72,
        DisplayName: "3 Maccabees",
        NumChapters: 7,
        NumVerses: []int{29,33,30,21,51,41,23},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 73,
        DisplayName: "4 Maccabees",
        NumChapters: 18,
        NumVerses: []int{35,24,21,26,38,35,23,29,32,21,27,19,27,20,32,25,24,24},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
          {
            Start: 73010004,
            End: 73010004,
          },
          {
            Start: 73011007,
            End: 73011008,
          },
        },
      },
      {
        BookNumber: 19,
        DisplayName: "Psalms",
        NumChapters: 151,
        NumVerses: []int{6,12,9,9,13,11,18,10,39,7,9,6,7,5,11,15,51,15,10,14,32,6,10,22,12,14,9,11,13,25,11,22,23,28,13,40,23,14,18,14,12,5,27,18,12,10,15,21,23,21,11,7,9,24,14,12,12,18,14,9,13,12,11,14,20,8,36,37,6,24,20,28,23,11,13,21,72,13,20,17,8,19,13,14,17,7,19,53,17,16,16,5,23,11,13,12,9,9,5,8,29,22,35,45,48,43,14,31,7,10,10,9,26,9,10,2,29,176,7,8,9,4,8,5,6,5,6,8,8,3,18,3,3,21,26,9,8,24,14,10,8,12,15,21,10,11,9,14,9,6,7},
        Superscripts: []int{3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 34, 35, 36, 37, 38, 39, 40, 41, 42, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 92, 98, 100, 101, 102, 103, 108, 109, 110, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 138, 139, 140, 141, 142, 143, 144, 145},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
          {
            Start: 19115005,
            End: 19115005,
          },
        },
      },
      {
        BookNumber: 74,
        DisplayName: "Odes",
        NumChapters: 14,
        NumVerses: []int{19,43,10,19,20,10,45,88,79,9,20,15,32,46},
        Superscripts: []int{1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
          {
            Start: 74005001,
            End: 74005008,
          },
          {
            Start: 74006001,
            End: 74006002,
          },
          {
            Start: 74007001,
            End: 74007025,
          },
          {
            Start: 74008001,
            End: 74008051,
          },
          {
            Start: 74009001,
            End: 74009045,
          },
          {
            Start: 74009056,
            End: 74009067,
          },
          {
            Start: 74011001,
            End: 74011009,
          },
          {
            Start: 74013001,
            End: 74013028,
          },
        },
      },
      {
        BookNumber: 20,
        DisplayName: "Proverbs",
        NumChapters: 36,
        NumVerses: []int{33,22,35,27,23,35,27,36,18,32,31,28,25,35,33,33,28,22,29,30,31,29,35,34,0,0,0,0,0,33,31,28,28,27,28,27},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
          {
            Start: 20004007,
            End: 20004007,
          },
          {
            Start: 20008033,
            End: 20008033,
          },
          {
            Start: 20011004,
            End: 20011004,
          },
          {
            Start: 20015031,
            End: 20015031,
          },
          {
            Start: 20016001,
            End: 20016001,
          },
          {
            Start: 20016003,
            End: 20016004,
          },
          {
            Start: 20016006,
            End: 20016006,
          },
          {
            Start: 20019001,
            End: 20019002,
          },
          {
            Start: 20020014,
            End: 20020022,
          },
          {
            Start: 20021005,
            End: 20021005,
          },
          {
            Start: 20022006,
            End: 20022006,
          },
          {
            Start: 20023023,
            End: 20023023,
          },
        },
      },
      {
        BookNumber: 21,
        DisplayName: "Ecclesiastes",
        NumChapters: 12,
        NumVerses: []int{18,26,22,17,19,12,29,17,18,20,10,14},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 22,
        DisplayName: "Song of Songs",
        NumChapters: 8,
        NumVerses: []int{17,17,11,16,16,12,14,14},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 18,
        DisplayName: "Job",
        NumChapters: 42,
        NumVerses: []int{22,13,26,21,27,30,21,22,35,22,20,25,28,22,35,22,16,21,29,29,34,30,17,25,6,14,23,28,25,31,40,22,33,37,16,33,24,41,30,32,26,17},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
          {
            Start: 18023014,
            End: 18023014,
          },
        },
      },
      {
        BookNumber: 75,
        DisplayName: "Wisdom of Solomon",
        NumChapters: 19,
        NumVerses: []int{16,24,19,20,23,25,30,21,18,21,26,27,19,31,19,29,20,25,22},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 76,
        DisplayName: "Sirach",
        NumChapters: 51,
        NumVerses: []int{30,18,31,31,15,37,36,19,18,31,34,18,26,27,20,30,32,33,30,31,28,27,27,34,26,29,30,26,28,25,31,24,33,26,24,27,31,34,35,30,27,25,33,23,26,20,25,25,16,29,30},
        Prologue: 36,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
          {
            Start: 76001005,
            End: 76001005,
          },
          {
            Start: 76001007,
            End: 76001007,
          },
          {
            Start: 76001021,
            End: 76001021,
          },
          {
            Start: 76003019,
            End: 76003019,
          },
          {
            Start: 76003025,
            End: 76003025,
          },
          {
            Start: 76006001,
            End: 76006001,
          },
          {
            Start: 76010021,
            End: 76010021,
          },
          {
            Start: 76011015,
            End: 76011016,
          },
          {
            Start: 76013014,
            End: 76013014,
          },
          {
            Start: 76016015,
            End: 76016016,
          },
          {
            Start: 76017005,
            End: 76017005,
          },
          {
            Start: 76017009,
            End: 76017009,
          },
          {
            Start: 76017016,
            End: 76017016,
          },
          {
            Start: 76017018,
            End: 76017018,
          },
          {
            Start: 76017021,
            End: 76017021,
          },
          {
            Start: 76018003,
            End: 76018003,
          },
          {
            Start: 76019018,
            End: 76019019,
          },
          {
            Start: 76019021,
            End: 76019021,
          },
          {
            Start: 76022007,
            End: 76022008,
          },
          {
            Start: 76024018,
            End: 76024018,
          },
          {
            Start: 76024024,
            End: 76024024,
          },
          {
            Start: 76025012,
            End: 76025012,
          },
          {
            Start: 76026019,
            End: 76026027,
          },
        },
      },
      {
        BookNumber: 77,
        DisplayName: "Solomon",
        NumChapters: 18,
        NumVerses: []int{8,37,12,25,19,6,10,34,11,8,9,6,12,10,13,15,46,12},
        Superscripts: []int{2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 28,
        DisplayName: "Hosea",
        NumChapters: 14,
        NumVerses: []int{9,25,5,19,15,11,16,14,17,15,11,15,15,10},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 30,
        DisplayName: "Amos",
        NumChapters: 9,
        NumVerses: []int{15,16,15,13,27,14,17,14,15},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 33,
        DisplayName: "Micah",
        NumChapters: 7,
        NumVerses: []int{16,13,12,14,14,16,20},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 29,
        DisplayName: "Joel",
        NumChapters: 4,
        NumVerses: []int{20,27,5,21},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 31,
        DisplayName: "Obadiah",
        NumChapters: 1,
        NumVerses: []int{21},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 32,
        DisplayName: "Jonah",
        NumChapters: 4,
        NumVerses: []int{16,11,10,11},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 34,
        DisplayName: "Nahum",
        NumChapters: 3,
        NumVerses: []int{14,14,19},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 35,
        DisplayName: "Habakkuk ",
        NumChapters: 3,
        NumVerses: []int{17,20,19},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 36,
        DisplayName: "Zephaniah",
        NumChapters: 3,
        NumVerses: []int{18,15,20},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 37,
        DisplayName: "Haggai",
        NumChapters: 2,
        NumVerses: []int{15,23},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 38,
        DisplayName: "Zechariah",
        NumChapters: 14,
        NumVerses: []int{17,17,10,14,11,15,14,23,17,12,17,14,9,21},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 39,
        DisplayName: "Malachi",
        NumChapters: 3,
        NumVerses: []int{14,17,24},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 23,
        DisplayName: "Isaiah",
        NumChapters: 66,
        NumVerses: []int{31,21,26,6,30,13,25,23,20,34,16,6,22,32,9,14,14,7,25,6,17,25,18,23,12,21,13,29,24,33,9,20,24,17,10,22,38,22,8,31,29,25,28,28,25,13,15,22,26,11,23,15,12,17,13,11,21,14,21,22,11,12,19,11,25,24},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 24,
        DisplayName: "Jeremiah",
        NumChapters: 52,
        NumVerses: []int{19,37,25,31,31,30,34,23,25,25,23,17,27,22,21,21,27,23,15,18,14,30,40,10,20,28,46,64,7,33,44,38,24,22,17,32,24,40,44,13,22,19,32,21,28,18,16,18,22,13,35,34},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
          {
            Start: 24002001,
            End: 24002001,
          },
          {
            Start: 24007001,
            End: 24007001,
          },
          {
            Start: 24007028,
            End: 24007028,
          },
          {
            Start: 24008011,
            End: 24008012,
          },
          {
            Start: 24010005,
            End: 24010008,
          },
          {
            Start: 24010010,
            End: 24010004,
          },
          {
            Start: 24010006,
            End: 24010010,
          },
          {
            Start: 24011007,
            End: 24011007,
          },
          {
            Start: 24017001,
            End: 24017004,
          },
          {
            Start: 24026001,
            End: 24026001,
          },
          {
            Start: 24026026,
            End: 24026026,
          },
          {
            Start: 24028045,
            End: 24028048,
          },
          {
            Start: 24030022,
            End: 24030022,
          },
          {
            Start: 24032001,
            End: 24032012,
          },
          {
            Start: 24032014,
            End: 24032014,
          },
          {
            Start: 24034001,
            End: 24034001,
          },
          {
            Start: 24034007,
            End: 24034007,
          },
          {
            Start: 24034013,
            End: 24034013,
          },
          {
            Start: 24034017,
            End: 24034017,
          },
          {
            Start: 24034021,
            End: 24034021,
          },
          {
            Start: 24036016,
            End: 24036020,
          },
          {
            Start: 24037010,
            End: 24037011,
          },
          {
            Start: 24037015,
            End: 24037015,
          },
          {
            Start: 24037022,
            End: 24037022,
          },
          {
            Start: 24046004,
            End: 24046013,
          },
          {
            Start: 24052002,
            End: 24052003,
          },
          {
            Start: 24052015,
            End: 24052015,
          },
          {
            Start: 24052028,
            End: 24052030,
          },
        },
      },
      {
        BookNumber: 78,
        DisplayName: "Baruch",
        NumChapters: 5,
        NumVerses: []int{22,35,38,37,9},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 25,
        DisplayName: "Lamentations",
        NumChapters: 5,
        NumVerses: []int{22,22,66,22,22},
        Superscripts: []int{1},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
          {
            Start: 25003022,
            End: 25003024,
          },
          {
            Start: 25003029,
            End: 25003029,
          },
        },
      },
      {
        BookNumber: 79,
        DisplayName: "Letter of Jeremiah",
        NumChapters: 1,
        NumVerses: []int{72},
        Superscripts: []int{1},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 26,
        DisplayName: "Ezekiel",
        NumChapters: 48,
        NumVerses: []int{28,10,27,17,17,14,27,18,11,22,25,28,23,23,8,63,24,32,14,44,37,31,49,27,17,21,36,26,21,26,18,32,33,31,15,38,28,23,29,49,26,20,27,31,25,24,23,35},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
          {
            Start: 26001014,
            End: 26001014,
          },
          {
            Start: 26010014,
            End: 26010014,
          },
          {
            Start: 26027031,
            End: 26027031,
          },
          {
            Start: 26032019,
            End: 26032019,
          },
          {
            Start: 26033026,
            End: 26033026,
          },
          {
            Start: 26040030,
            End: 26040030,
          },
        },
      },
      {
        BookNumber: 27,
        DisplayName: "Daniel",
        NumChapters: 12,
        NumVerses: []int{21,49,97,37,30,29,28,27,27,21,45,13},
        Superscripts: []int{5},
        Prologue: 0,
        Parallels: []VersionBibleRange{
          {
            Start: 27001001,
            End: 27001021,
          },
          {
            Start: 27002001,
            End: 27002049,
          },
          {
            Start: 27003001,
            End: 27003097,
          },
          {
            Start: 27004001,
            End: 27004037,
          },
          {
            Start: 27005001,
            End: 27005030,
          },
          {
            Start: 27006001,
            End: 27006029,
          },
          {
            Start: 27007001,
            End: 27007028,
          },
          {
            Start: 27008001,
            End: 27008027,
          },
          {
            Start: 27009001,
            End: 27009027,
          },
          {
            Start: 27010001,
            End: 27010021,
          },
          {
            Start: 27011001,
            End: 27011045,
          },
          {
            Start: 27012001,
            End: 27012013,
          },
        },
        MissingSections: []VersionBibleRange{
          {
            Start: 27004001,
            End: 27004003,
          },
          {
            Start: 27004006,
            End: 27004009,
          },
          {
            Start: 27004011,
            End: 27004011,
          },
          {
            Start: 27004013,
            End: 27004010,
          },
          {
            Start: 27004012,
            End: 27004012,
          },
          {
            Start: 27004035,
            End: 27004035,
          },
          {
            Start: 27005014,
            End: 27005015,
          },
          {
            Start: 27005018,
            End: 27005022,
          },
          {
            Start: 27005024,
            End: 27005025,
          },
          {
            Start: 27005027,
            End: 27005028,
          },
        },
      },
      {
        BookNumber: 80,
        DisplayName: "Susanna",
        NumChapters: 1,
        NumVerses: []int{63},
        Prologue: 0,
        Parallels: []VersionBibleRange{
          {
            Start: 80001001,
            End: 80001064,
          },
        },
        MissingSections: []VersionBibleRange{
          {
            Start: 80001001,
            End: 80001005,
          },
          {
            Start: 80001008,
            End: 80001008,
          },
          {
            Start: 80001011,
            End: 80001011,
          },
          {
            Start: 80001014,
            End: 80001018,
          },
          {
            Start: 80001020,
            End: 80001021,
          },
          {
            Start: 80001024,
            End: 80001027,
          },
          {
            Start: 80001042,
            End: 80001043,
          },
          {
            Start: 80001045,
            End: 80001047,
          },
          {
            Start: 80001049,
            End: 80001050,
          },
          {
            Start: 80001061,
            End: 80001062,
          },
        },
      },
      {
        BookNumber: 81,
        DisplayName: "Bel and the Dragon",
        NumChapters: 1,
        NumVerses: []int{42},
        Prologue: 0,
        Parallels: []VersionBibleRange{
          {
            Start: 81001001,
            End: 81001042,
          },
        },
        MissingSections: []VersionBibleRange{
          {
            Start: 81001012,
            End: 81001012,
          },
          {
            Start: 81001016,
            End: 81001017,
          },
          {
            Start: 81001029,
            End: 81001029,
          },
          {
            Start: 81001032,
            End: 81001032,
          },
        },
      },
    },
  },
  {
    Name: "gnt",
    FullName: "Greek New Testament",
    Language: "greek",
    LanguageHeadings: "greek",
    Books: []VersionBookData{
      {
        BookNumber: 40,
        DisplayName: "ΚΑΤΑ ΜΑΘΘΑΙΟΝ",
        NumChapters: 28,
        NumVerses: []int{25,23,17,25,48,34,29,34,38,42,30,50,58,36,39,28,27,35,30,34,46,46,39,51,46,75,66,20},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 41,
        DisplayName: "ΚΑΤΑ ΜΑΡΚΟΝ",
        NumChapters: 16,
        NumVerses: []int{45,28,35,41,43,56,37,38,50,52,33,44,37,72,47,20},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 42,
        DisplayName: "ΚΑΤΑ ΛΟΥΚΑΝ",
        NumChapters: 24,
        NumVerses: []int{80,52,38,44,39,49,50,56,62,42,54,59,35,35,32,31,37,43,48,47,38,71,56,53},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 43,
        DisplayName: "ΚΑΤΑ ΙΩΑΝΝΗΝ",
        NumChapters: 21,
        NumVerses: []int{51,25,36,54,47,71,53,59,41,42,57,50,38,31,27,33,26,40,42,31,25},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 44,
        DisplayName: "ΠΡΑΞΕΙΣ ΑΠΟΣΤΟΛΩΝ",
        NumChapters: 28,
        NumVerses: []int{26,47,26,37,42,15,60,40,43,48,30,25,52,28,41,40,34,28,41,38,40,30,35,27,27,32,44,31},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 45,
        DisplayName: "ΠΡΟΣ ΡΩΜΑΙΟΥΣ",
        NumChapters: 16,
        NumVerses: []int{32,29,31,25,21,23,25,39,33,21,36,21,14,23,33,27},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 46,
        DisplayName: "ΠΡΟΣ ΚΟΡΙΝΘΙΟΥΣ Ά",
        NumChapters: 16,
        NumVerses: []int{31,16,23,21,13,20,40,13,27,33,34,31,13,40,58,24},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 47,
        DisplayName: "ΠΡΟΣ ΚΟΡΙΝΘΙΟΥΣ Β́",
        NumChapters: 13,
        NumVerses: []int{24,17,18,18,21,18,16,24,15,18,33,21,14},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 48,
        DisplayName: "ΠΡΟΣ ΓΑΛΑΤΑΣ",
        NumChapters: 6,
        NumVerses: []int{24,21,29,31,26,18},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 49,
        DisplayName: "ΠΡΟΣ ΕΦΕΣΙΟΥΣ",
        NumChapters: 6,
        NumVerses: []int{23,22,21,32,33,24},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 50,
        DisplayName: "ΠΡΟΣ ΦΙΛΙΠΠΗΣΙΟΥΣ",
        NumChapters: 4,
        NumVerses: []int{30,30,21,23},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 51,
        DisplayName: "ΠΡΟΣ ΚΟΛΟΣΣΑΕΙΣ",
        NumChapters: 4,
        NumVerses: []int{29,23,25,18},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 52,
        DisplayName: "ΠΡΟΣ ΘΕΣΣΑΛΟΝΙΚΕΙΣ Α",
        NumChapters: 5,
        NumVerses: []int{10,20,13,18,28},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 53,
        DisplayName: "ΠΡΟΣ ΘΕΣΣΑΛΟΝΙΚΕΙΣ Β́",
        NumChapters: 3,
        NumVerses: []int{12,17,18},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 54,
        DisplayName: "ΠΡΟΣ ΤΙΜΟΘΕΟΝ Ά",
        NumChapters: 6,
        NumVerses: []int{20,15,16,16,25,21},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 55,
        DisplayName: "ΠΡΟΣ ΤΙΜΟΘΕΟΝ Β́",
        NumChapters: 4,
        NumVerses: []int{18,26,17,22},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 56,
        DisplayName: "ΠΡΟΣ ΤΙΤΟΝ",
        NumChapters: 3,
        NumVerses: []int{16,15,15},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 57,
        DisplayName: "ΠΡΟΣ ΦΙΛΗΜΟΝΑ",
        NumChapters: 1,
        NumVerses: []int{25},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 58,
        DisplayName: "ΠΡΟΣ ΕΒΡΑΙΟΥΣ",
        NumChapters: 13,
        NumVerses: []int{14,18,19,16,14,20,28,13,28,39,40,29,25},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 59,
        DisplayName: "ΙΑΚΩΒΟΥ ΕΠΙΣΤΟΛΗ",
        NumChapters: 5,
        NumVerses: []int{27,26,18,17,20},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 60,
        DisplayName: "ΠΕΤΡΟΥ ΕΠΙΣΤΟΛΗ ΠΡΩΤΗ",
        NumChapters: 5,
        NumVerses: []int{25,25,22,19,14},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 61,
        DisplayName: "ΠΕΤΡΟΥ ΕΠΙΣΤΟΛΗ ΔΕΥΤΕΡΑ",
        NumChapters: 3,
        NumVerses: []int{21,22,18},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 62,
        DisplayName: "ΙΩΑΝΝΟΥ ΕΠΙΣΤΟΛΗ ΠΡΩΤΗ",
        NumChapters: 5,
        NumVerses: []int{10,29,24,21,21},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 63,
        DisplayName: "ΙΩΑΝΝΟΥ ΕΠΙΣΤΟΛΗ ΔΕΥΤΕΡΑ",
        NumChapters: 1,
        NumVerses: []int{13},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 64,
        DisplayName: "ΙΩΑΝΝΟΥ ΕΠΙΣΤΟΛΗ ΤΡΙΤΗ",
        NumChapters: 1,
        NumVerses: []int{15},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 65,
        DisplayName: "ΙΟΥΔΑ ΕΠΙΣΤΟΛΗ",
        NumChapters: 1,
        NumVerses: []int{25},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 66,
        DisplayName: "ΑΠΟΚΑΛΥΨΙΣ ΙΩΑΝΝΟΥ",
        NumChapters: 22,
        NumVerses: []int{20,29,22,11,14,17,17,13,21,11,19,18,18,20,8,21,18,24,21,15,27,21},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
    },
  },
  {
    Name: "hot",
    FullName: "Hebrew Old Testament",
    Language: "hebrew",
    LanguageHeadings: "english",
    Books: []VersionBookData{
      {
        BookNumber: 1,
        DisplayName: "Genesis",
        NumChapters: 50,
        NumVerses: []int{31,25,24,26,32,22,24,22,29,32,32,20,18,24,21,16,27,33,38,18,34,24,20,67,34,35,46,22,35,43,55,32,20,31,29,43,36,30,23,23,57,38,34,34,28,34,31,22,33,26},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 2,
        DisplayName: "Exodus",
        NumChapters: 40,
        NumVerses: []int{22,25,22,31,23,30,25,32,35,29,10,51,22,31,27,36,16,27,25,26,36,31,33,18,40,37,21,43,46,38,18,35,23,35,35,38,29,31,43,38},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 3,
        DisplayName: "Leviticus",
        NumChapters: 27,
        NumVerses: []int{17,16,17,35,19,30,38,36,24,20,47,8,59,57,33,34,16,30,37,27,24,33,44,23,55,46,34},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 4,
        DisplayName: "Numbers",
        NumChapters: 36,
        NumVerses: []int{54,34,51,49,31,27,89,26,23,36,35,16,33,45,41,50,13,32,22,29,35,41,30,25,18,65,23,31,40,16,54,42,56,29,34,13},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 5,
        DisplayName: "Deuteronomy",
        NumChapters: 34,
        NumVerses: []int{46,37,29,49,33,25,26,20,29,22,32,32,18,29,23,22,20,22,21,20,23,30,25,22,19,19,26,68,29,20,30,52,29,12},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 6,
        DisplayName: "Joshua",
        NumChapters: 24,
        NumVerses: []int{18,24,17,24,15,27,26,35,27,43,23,24,33,15,63,10,18,28,51,9,45,34,16,33},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 7,
        DisplayName: "Judges",
        NumChapters: 21,
        NumVerses: []int{36,23,31,24,31,40,25,35,57,18,40,15,25,20,20,31,13,31,30,48,25},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 9,
        DisplayName: "1 Samuel",
        NumChapters: 31,
        NumVerses: []int{28,36,21,22,12,21,17,22,27,27,15,25,23,52,35,23,58,30,24,42,15,23,29,22,44,25,12,25,11,31,13},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 10,
        DisplayName: "2 Samuel",
        NumChapters: 24,
        NumVerses: []int{27,32,39,12,25,23,29,18,13,19,27,31,39,33,37,23,29,33,43,26,22,51,39,25},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 11,
        DisplayName: "1 Kings",
        NumChapters: 22,
        NumVerses: []int{53,46,28,34,18,38,51,66,28,29,43,33,34,31,34,34,24,46,21,43,29,53},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 12,
        DisplayName: "2 Kings",
        NumChapters: 25,
        NumVerses: []int{18,25,27,44,27,33,20,29,37,36,21,21,25,29,38,20,41,37,37,21,26,20,37,20,30},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 23,
        DisplayName: "Isaiah",
        NumChapters: 66,
        NumVerses: []int{31,22,26,6,30,13,25,22,21,34,16,6,22,32,9,14,14,7,25,6,17,25,18,23,12,21,13,29,24,33,9,20,24,17,10,22,38,22,8,31,29,25,28,28,25,13,15,22,26,11,23,15,12,17,13,12,21,14,21,22,11,12,19,12,25,24},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 24,
        DisplayName: "Jeremiah",
        NumChapters: 52,
        NumVerses: []int{19,37,25,31,31,30,34,22,26,25,23,17,27,22,21,21,27,23,15,18,14,30,40,10,38,24,22,17,32,24,40,44,26,22,19,32,21,28,18,16,18,22,13,30,5,28,7,47,39,46,64,34},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 26,
        DisplayName: "Ezekiel",
        NumChapters: 48,
        NumVerses: []int{28,10,27,17,17,14,27,18,11,22,25,28,23,23,8,63,24,32,14,49,32,31,49,27,17,21,36,26,21,26,18,32,33,31,15,38,28,23,29,49,26,20,27,31,25,24,23,35},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 28,
        DisplayName: "Hosea",
        NumChapters: 14,
        NumVerses: []int{11,23,5,19,15,11,16,14,17,15,12,14,16,9},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 29,
        DisplayName: "Joel",
        NumChapters: 3,
        NumVerses: []int{20,32,21},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 30,
        DisplayName: "Amos",
        NumChapters: 9,
        NumVerses: []int{15,16,15,13,27,14,17,14,15},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 31,
        DisplayName: "Obadiah",
        NumChapters: 1,
        NumVerses: []int{21},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 32,
        DisplayName: "Jonah",
        NumChapters: 4,
        NumVerses: []int{17,10,10,11},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 33,
        DisplayName: "Micah",
        NumChapters: 7,
        NumVerses: []int{16,13,12,13,15,16,20},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 34,
        DisplayName: "Nahum",
        NumChapters: 3,
        NumVerses: []int{15,13,19},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 35,
        DisplayName: "Habakkuk ",
        NumChapters: 3,
        NumVerses: []int{17,20,19},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 36,
        DisplayName: "Zephaniah",
        NumChapters: 3,
        NumVerses: []int{18,15,20},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 37,
        DisplayName: "Haggai",
        NumChapters: 2,
        NumVerses: []int{15,23},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 38,
        DisplayName: "Zechariah",
        NumChapters: 14,
        NumVerses: []int{21,13,10,14,11,15,14,23,17,12,17,14,9,21},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 39,
        DisplayName: "Malachi",
        NumChapters: 4,
        NumVerses: []int{14,17,18,6},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 19,
        DisplayName: "Psalms",
        NumChapters: 150,
        NumVerses: []int{6,12,8,8,12,10,17,9,20,18,7,8,6,7,5,11,15,50,14,9,13,31,6,10,22,12,14,9,11,12,24,11,22,22,28,12,40,22,13,17,13,11,5,26,17,11,9,14,20,23,19,9,6,7,23,13,11,11,17,12,8,12,11,10,13,20,7,35,36,5,24,20,28,23,10,12,20,72,13,19,16,8,18,12,13,17,7,18,52,17,16,15,5,23,11,13,12,9,9,5,8,28,22,35,45,48,43,13,31,7,10,10,9,8,18,19,2,29,176,7,8,9,4,8,5,6,5,6,8,8,3,18,3,3,21,26,9,8,24,13,10,7,12,15,21,10,20,14,9,6},
        Superscripts: []int{3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 34, 35, 36, 37, 38, 39, 40, 41, 42, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 92, 98, 100, 101, 102, 103, 108, 109, 110, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 138, 139, 140, 141, 142, 143, 144, 145},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 18,
        DisplayName: "Job",
        NumChapters: 42,
        NumVerses: []int{22,13,26,21,27,30,21,22,35,22,20,25,28,22,35,22,16,21,29,29,34,30,17,25,6,14,23,28,25,31,40,22,33,37,16,33,24,41,30,24,34,17},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 20,
        DisplayName: "Proverbs",
        NumChapters: 31,
        NumVerses: []int{33,22,35,27,23,35,27,36,18,32,31,28,25,35,33,33,28,24,29,30,31,29,35,34,28,28,27,28,27,33,31},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 8,
        DisplayName: "Ruth",
        NumChapters: 4,
        NumVerses: []int{22,23,18,22},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 22,
        DisplayName: "Song of Songs",
        NumChapters: 8,
        NumVerses: []int{17,17,11,16,16,13,13,14},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 21,
        DisplayName: "Ecclesiastes",
        NumChapters: 12,
        NumVerses: []int{18,26,22,16,20,12,29,17,18,20,10,14},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 25,
        DisplayName: "Lamentations",
        NumChapters: 5,
        NumVerses: []int{22,22,66,22,22},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 17,
        DisplayName: "Esther",
        NumChapters: 10,
        NumVerses: []int{22,23,15,17,14,14,10,17,32,3},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 27,
        DisplayName: "Daniel",
        NumChapters: 12,
        NumVerses: []int{21,49,30,37,31,28,28,27,27,21,45,13},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 15,
        DisplayName: "Ezra",
        NumChapters: 10,
        NumVerses: []int{11,70,13,24,17,22,28,36,15,44},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 16,
        DisplayName: "Nehemiah",
        NumChapters: 13,
        NumVerses: []int{11,20,32,23,19,19,73,18,38,39,36,47,31},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 13,
        DisplayName: "1 Chronicles",
        NumChapters: 29,
        NumVerses: []int{54,55,24,43,26,81,40,40,44,14,47,40,14,17,29,43,27,17,19,8,30,19,32,31,31,32,34,21,30},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 14,
        DisplayName: "2 Chronicles",
        NumChapters: 36,
        NumVerses: []int{17,18,17,22,14,42,22,18,31,19,23,16,22,15,19,14,19,34,11,37,20,12,21,27,28,23,9,27,36,27,21,33,25,33,27,23},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
    },
  },
  {
    Name: "esv",
    FullName: "English Standard Version",
    Language: "english",
    LanguageHeadings: "english",
    Books: []VersionBookData{
      {
        BookNumber: 1,
        DisplayName: "Genesis",
        NumChapters: 50,
        NumVerses: []int{31,25,24,26,32,22,24,22,29,32,32,20,18,24,21,16,27,33,38,18,34,24,20,67,34,35,46,22,35,43,55,32,20,31,29,43,36,30,23,23,57,38,34,34,28,34,31,22,33,26},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 2,
        DisplayName: "Exodus",
        NumChapters: 40,
        NumVerses: []int{22,25,22,31,23,30,25,32,35,29,10,51,22,31,27,36,16,27,25,26,36,31,33,18,40,37,21,43,46,38,18,35,23,35,35,38,29,31,43,38},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 3,
        DisplayName: "Leviticus",
        NumChapters: 27,
        NumVerses: []int{17,16,17,35,19,30,38,36,24,20,47,8,59,57,33,34,16,30,37,27,24,33,44,23,55,46,34},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 4,
        DisplayName: "Numbers",
        NumChapters: 36,
        NumVerses: []int{54,34,51,49,31,27,89,26,23,36,35,16,33,45,41,50,13,32,22,29,35,41,30,25,18,65,23,31,40,16,54,42,56,29,34,13},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 5,
        DisplayName: "Deuteronomy",
        NumChapters: 34,
        NumVerses: []int{46,37,29,49,33,25,26,20,29,22,32,32,18,29,23,22,20,22,21,20,23,30,25,22,19,19,26,68,29,20,30,52,29,12},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 6,
        DisplayName: "Joshua",
        NumChapters: 24,
        NumVerses: []int{18,24,17,24,15,27,26,35,27,43,23,24,33,15,63,10,18,28,51,9,45,34,16,33},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 7,
        DisplayName: "Judges",
        NumChapters: 21,
        NumVerses: []int{36,23,31,24,31,40,25,35,57,18,40,15,25,20,20,31,13,31,30,48,25},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 8,
        DisplayName: "Ruth",
        NumChapters: 4,
        NumVerses: []int{22,23,18,22},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 9,
        DisplayName: "1 Samuel",
        NumChapters: 31,
        NumVerses: []int{28,36,21,22,12,21,17,22,27,27,15,25,23,52,35,23,58,30,24,42,15,23,29,22,44,25,12,25,11,31,13},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 10,
        DisplayName: "2 Samuel",
        NumChapters: 24,
        NumVerses: []int{27,32,39,12,25,23,29,18,13,19,27,31,39,33,37,23,29,33,43,26,22,51,39,25},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 11,
        DisplayName: "1 Kings",
        NumChapters: 22,
        NumVerses: []int{53,46,28,34,18,38,51,66,28,29,43,33,34,31,34,34,24,46,21,43,29,53},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 12,
        DisplayName: "2 Kings",
        NumChapters: 25,
        NumVerses: []int{18,25,27,44,27,33,20,29,37,36,21,21,25,29,38,20,41,37,37,21,26,20,37,20,30},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 13,
        DisplayName: "1 Chronicles",
        NumChapters: 29,
        NumVerses: []int{54,55,24,43,26,81,40,40,44,14,47,40,14,17,29,43,27,17,19,8,30,19,32,31,31,32,34,21,30},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 14,
        DisplayName: "2 Chronicles",
        NumChapters: 36,
        NumVerses: []int{17,18,17,22,14,42,22,18,31,19,23,16,22,15,19,14,19,34,11,37,20,12,21,27,28,23,9,27,36,27,21,33,25,33,27,23},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 15,
        DisplayName: "Ezra",
        NumChapters: 10,
        NumVerses: []int{11,70,13,24,17,22,28,36,15,44},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 16,
        DisplayName: "Nehemiah",
        NumChapters: 13,
        NumVerses: []int{11,20,32,23,19,19,73,18,38,39,36,47,31},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 17,
        DisplayName: "Esther",
        NumChapters: 10,
        NumVerses: []int{22,23,15,17,14,14,10,17,32,3},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 18,
        DisplayName: "Job",
        NumChapters: 42,
        NumVerses: []int{22,13,26,21,27,30,21,22,35,22,20,25,28,22,35,22,16,21,29,29,34,30,17,25,6,14,23,28,25,31,40,22,33,37,16,33,24,41,30,24,34,17},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 19,
        DisplayName: "Psalms",
        NumChapters: 150,
        NumVerses: []int{6,12,8,8,12,10,17,9,20,18,7,8,6,7,5,11,15,50,14,9,13,31,6,10,22,12,14,9,11,12,24,11,22,22,28,12,40,22,13,17,13,11,5,26,17,11,9,14,20,23,19,9,6,7,23,13,11,11,17,12,8,12,11,10,13,20,7,35,36,5,24,20,28,23,10,12,20,72,13,19,16,8,18,12,13,17,7,18,52,17,16,15,5,23,11,13,12,9,9,5,8,28,22,35,45,48,43,13,31,7,10,10,9,8,18,19,2,29,176,7,8,9,4,8,5,6,5,6,8,8,3,18,3,3,21,26,9,8,24,13,10,7,12,15,21,10,20,14,9,6},
        Superscripts: []int{3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 34, 35, 36, 37, 38, 39, 40, 41, 42, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 92, 98, 100, 101, 102, 103, 108, 109, 110, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 138, 139, 140, 141, 142, 143, 144, 145},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 20,
        DisplayName: "Proverbs",
        NumChapters: 31,
        NumVerses: []int{33,22,35,27,23,35,27,36,18,32,31,28,25,35,33,33,28,24,29,30,31,29,35,34,28,28,27,28,27,33,31},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 21,
        DisplayName: "Ecclesiastes",
        NumChapters: 12,
        NumVerses: []int{18,26,22,16,20,12,29,17,18,20,10,14},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 22,
        DisplayName: "Song of Solomon",
        NumChapters: 8,
        NumVerses: []int{17,17,11,16,16,13,13,14},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 23,
        DisplayName: "Isaiah",
        NumChapters: 66,
        NumVerses: []int{31,22,26,6,30,13,25,22,21,34,16,6,22,32,9,14,14,7,25,6,17,25,18,23,12,21,13,29,24,33,9,20,24,17,10,22,38,22,8,31,29,25,28,28,25,13,15,22,26,11,23,15,12,17,13,12,21,14,21,22,11,12,19,12,25,24},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 24,
        DisplayName: "Jeremiah",
        NumChapters: 52,
        NumVerses: []int{19,37,25,31,31,30,34,22,26,25,23,17,27,22,21,21,27,23,15,18,14,30,40,10,38,24,22,17,32,24,40,44,26,22,19,32,21,28,18,16,18,22,13,30,5,28,7,47,39,46,64,34},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 25,
        DisplayName: "Lamentations",
        NumChapters: 5,
        NumVerses: []int{22,22,66,22,22},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 26,
        DisplayName: "Ezekiel",
        NumChapters: 48,
        NumVerses: []int{28,10,27,17,17,14,27,18,11,22,25,28,23,23,8,63,24,32,14,49,32,31,49,27,17,21,36,26,21,26,18,32,33,31,15,38,28,23,29,49,26,20,27,31,25,24,23,35},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 27,
        DisplayName: "Daniel",
        NumChapters: 12,
        NumVerses: []int{21,49,30,37,31,28,28,27,27,21,45,13},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 28,
        DisplayName: "Hosea",
        NumChapters: 14,
        NumVerses: []int{11,23,5,19,15,11,16,14,17,15,12,14,16,9},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 29,
        DisplayName: "Joel",
        NumChapters: 3,
        NumVerses: []int{20,32,21},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 30,
        DisplayName: "Amos",
        NumChapters: 9,
        NumVerses: []int{15,16,15,13,27,14,17,14,15},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 31,
        DisplayName: "Obadiah",
        NumChapters: 1,
        NumVerses: []int{21},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 32,
        DisplayName: "Jonah",
        NumChapters: 4,
        NumVerses: []int{17,10,10,11},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 33,
        DisplayName: "Micah",
        NumChapters: 7,
        NumVerses: []int{16,13,12,13,15,16,20},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 34,
        DisplayName: "Nahum",
        NumChapters: 3,
        NumVerses: []int{15,13,19},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 35,
        DisplayName: "Habakkuk ",
        NumChapters: 3,
        NumVerses: []int{17,20,19},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 36,
        DisplayName: "Zephaniah",
        NumChapters: 3,
        NumVerses: []int{18,15,20},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 37,
        DisplayName: "Haggai",
        NumChapters: 2,
        NumVerses: []int{15,23},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 38,
        DisplayName: "Zechariah",
        NumChapters: 14,
        NumVerses: []int{21,13,10,14,11,15,14,23,17,12,17,14,9,21},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 39,
        DisplayName: "Malachi",
        NumChapters: 4,
        NumVerses: []int{14,17,18,6},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 40,
        DisplayName: "Matthew",
        NumChapters: 28,
        NumVerses: []int{25,23,17,25,48,34,29,34,38,42,30,50,58,36,39,28,27,35,30,34,46,46,39,51,46,75,66,20},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
          {
            Start: 40012047,
            End: 40012047,
          },
          {
            Start: 40017021,
            End: 40017021,
          },
          {
            Start: 40018011,
            End: 40018011,
          },
          {
            Start: 40023014,
            End: 40023014,
          },
        },
      },
      {
        BookNumber: 41,
        DisplayName: "Mark",
        NumChapters: 16,
        NumVerses: []int{45,28,35,41,43,56,37,38,50,52,33,44,37,72,47,20},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
          {
            Start: 41007016,
            End: 41007016,
          },
          {
            Start: 41009044,
            End: 41009044,
          },
          {
            Start: 41009046,
            End: 41009046,
          },
          {
            Start: 41011026,
            End: 41011026,
          },
          {
            Start: 41015028,
            End: 41015028,
          },
        },
      },
      {
        BookNumber: 42,
        DisplayName: "Luke",
        NumChapters: 24,
        NumVerses: []int{80,52,38,44,39,49,50,56,62,42,54,59,35,35,32,31,37,43,48,47,38,71,56,53},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
          {
            Start: 42017036,
            End: 42017036,
          },
          {
            Start: 42023017,
            End: 42023017,
          },
        },
      },
      {
        BookNumber: 43,
        DisplayName: "John",
        NumChapters: 21,
        NumVerses: []int{51,25,36,54,47,71,53,59,41,42,57,50,38,31,27,33,26,40,42,31,25},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
          {
            Start: 43005004,
            End: 43005004,
          },
        },
      },
      {
        BookNumber: 44,
        DisplayName: "Acts",
        NumChapters: 28,
        NumVerses: []int{26,47,26,37,42,15,60,40,43,48,30,25,52,28,41,40,34,28,41,38,40,30,35,27,27,32,44,31},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
          {
            Start: 44008037,
            End: 44008037,
          },
          {
            Start: 44015034,
            End: 44015034,
          },
          {
            Start: 44024007,
            End: 44024007,
          },
          {
            Start: 44028029,
            End: 44028029,
          },
        },
      },
      {
        BookNumber: 45,
        DisplayName: "Romans",
        NumChapters: 16,
        NumVerses: []int{32,29,31,25,21,23,25,39,33,21,36,21,14,23,33,27},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
          {
            Start: 45016024,
            End: 45016024,
          },
        },
      },
      {
        BookNumber: 46,
        DisplayName: "1 Corinthians",
        NumChapters: 16,
        NumVerses: []int{31,16,23,21,13,20,40,13,27,33,34,31,13,40,58,24},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 47,
        DisplayName: "2 Corinthians",
        NumChapters: 13,
        NumVerses: []int{24,17,18,18,21,18,16,24,15,18,33,21,14},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 48,
        DisplayName: "Galatians",
        NumChapters: 6,
        NumVerses: []int{24,21,29,31,26,18},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 49,
        DisplayName: "Ephesians",
        NumChapters: 6,
        NumVerses: []int{23,22,21,32,33,24},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 50,
        DisplayName: "Philippians",
        NumChapters: 4,
        NumVerses: []int{30,30,21,23},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 51,
        DisplayName: "Colossians",
        NumChapters: 4,
        NumVerses: []int{29,23,25,18},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 52,
        DisplayName: "1 Thessalonians",
        NumChapters: 5,
        NumVerses: []int{10,20,13,18,28},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 53,
        DisplayName: "2 Thessalonians",
        NumChapters: 3,
        NumVerses: []int{12,17,18},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 54,
        DisplayName: "1 Timothy",
        NumChapters: 6,
        NumVerses: []int{20,15,16,16,25,21},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 55,
        DisplayName: "2 Timothy",
        NumChapters: 4,
        NumVerses: []int{18,26,17,22},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 56,
        DisplayName: "Titus",
        NumChapters: 3,
        NumVerses: []int{16,15,15},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 57,
        DisplayName: "Philemon",
        NumChapters: 1,
        NumVerses: []int{25},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 58,
        DisplayName: "Hebrews",
        NumChapters: 13,
        NumVerses: []int{14,18,19,16,14,20,28,13,28,39,40,29,25},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 59,
        DisplayName: "James",
        NumChapters: 5,
        NumVerses: []int{27,26,18,17,20},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 60,
        DisplayName: "1 Peter",
        NumChapters: 5,
        NumVerses: []int{25,25,22,19,14},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 61,
        DisplayName: "2 Peter",
        NumChapters: 3,
        NumVerses: []int{21,22,18},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 62,
        DisplayName: "1 John",
        NumChapters: 5,
        NumVerses: []int{10,29,24,21,21},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 63,
        DisplayName: "2 John",
        NumChapters: 1,
        NumVerses: []int{13},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 64,
        DisplayName: "3 John",
        NumChapters: 1,
        NumVerses: []int{15},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 65,
        DisplayName: "Jude",
        NumChapters: 1,
        NumVerses: []int{25},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
      {
        BookNumber: 66,
        DisplayName: "Revelation",
        NumChapters: 22,
        NumVerses: []int{20,29,22,11,14,17,17,13,21,11,19,17,18,20,8,21,18,24,21,15,27,21},
        Prologue: 0,
        Parallels: []VersionBibleRange{
        },
        MissingSections: []VersionBibleRange{
        },
      },
    },
  },
}
