// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {menu} from '../models';
import {scripture} from '../models';
import {data} from '../models';
import {settings} from '../models';

export function DisableMenu():Promise<void>;

export function GetEnvironmentInfo():Promise<app.EnvironmentInfo>;

export function GetMenu():Promise<menu.Menu>;

export function GetScriptureSection(arg1:scripture.ScriptureRange):Promise<Array<data.ScriptureSection>>;

export function GetScriptureWord(arg1:scripture.ScriptureVersion,arg2:scripture.ScriptureRef,arg3:number):Promise<data.ScriptureWordData>;

export function GetSettings():Promise<settings.SettingsValues>;

export function LoadMenu():Promise<void>;

export function ResetSetting(arg1:Array<string>):Promise<any>;

export function UpdateSetting(arg1:Array<string>,arg2:any):Promise<boolean>;
