// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetEnvironmentInfo() {
  return window['go']['app']['App']['GetEnvironmentInfo']();
}

export function GetScriptureSections(arg1) {
  return window['go']['app']['App']['GetScriptureSections'](arg1);
}

export function GetScriptureWord(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetScriptureWord'](arg1, arg2, arg3);
}

export function Menu() {
  return window['go']['app']['App']['Menu']();
}

export function Throw(arg1) {
  return window['go']['app']['App']['Throw'](arg1);
}
