// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeMenu() {
  return window['go']['app']['App']['ChangeMenu']();
}

export function GetEnvironmentInfo() {
  return window['go']['app']['App']['GetEnvironmentInfo']();
}

export function GetMenu() {
  return window['go']['app']['App']['GetMenu']();
}

export function GetScriptureSection(arg1) {
  return window['go']['app']['App']['GetScriptureSection'](arg1);
}

export function GetScriptureWord(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetScriptureWord'](arg1, arg2, arg3);
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function Throw(arg1) {
  return window['go']['app']['App']['Throw'](arg1);
}

export function UpdateSetting(arg1, arg2) {
  return window['go']['app']['App']['UpdateSetting'](arg1, arg2);
}
