// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

export function Assert(prefix: string, cond: boolean, msg: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3862035617, prefix, cond, msg) as any;
    return $resultPromise;
}

export function Log(prefix: string, msg: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3180178175, prefix, msg) as any;
    return $resultPromise;
}
