// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class ScriptureRange {
    "version": ScriptureVersion;
    "start": ScriptureRef;
    "end": ScriptureRef;

    /** Creates a new ScriptureRange instance. */
    constructor($$source: Partial<ScriptureRange> = {}) {
        if (!("version" in $$source)) {
            this["version"] = ("" as ScriptureVersion);
        }
        if (!("start" in $$source)) {
            this["start"] = (0 as ScriptureRef);
        }
        if (!("end" in $$source)) {
            this["end"] = (0 as ScriptureRef);
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScriptureRange instance from a string or object.
     */
    static createFrom($$source: any = {}): ScriptureRange {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScriptureRange($$parsedSource as Partial<ScriptureRange>);
    }
}

export type ScriptureRef = number;

export enum ScriptureRefStringType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    StringShort = 0,
    StringLong = 1,
    StringChapter = 2,
    StringBook = 3,
    StringVersionBook = 4,
};

export type ScriptureVersion = string;
